#!/usr/bin/env ruby
# frozen_string_literal: true 

require 'mhartl_palindrome'
require 'open-uri'

lines = URI.open('https://cdn.learnenough.com/phrases.txt').readlines
pp lines
# lines = open('https://learnenough.s3-us-west-2.amazonaws.com/phrases.txt').readlines
lines.each do |line|
  if line.palindrome?
    puts "palindrome detected: #{line}"
  end
end
